"""fix invisible nullable=false

Revision ID: 0937c3cc738d
Revises: 543868515076
Create Date: 2025-12-28 13:33:30.040884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0937c3cc738d'
down_revision: Union[str, Sequence[str], None] = '543868515076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.execute("UPDATE cards SET invisible = False WHERE invisible IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
