"""init

Revision ID: 41053f363323
Revises: 
Create Date: 2025-12-20 14:16:25.200952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41053f363323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'preview_image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cards', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cards', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cards', 'preview_image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
