"""add invisible field into Card

Revision ID: 543868515076
Revises: 8f54f1b69b00
Create Date: 2025-12-27 18:04:43.335807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543868515076'
down_revision: Union[str, Sequence[str], None] = '8f54f1b69b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('invisible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'invisible')
    # ### end Alembic commands ###
