"""card nullable

Revision ID: 7561100718d7
Revises: 3558d5dc3014
Create Date: 2026-06-17 22:21:49.030628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7561100718d7'
down_revision: Union[str, Sequence[str], None] = '3558d5dc3014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_action', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_action', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
