"""add parent_id  column to Category

Revision ID: c92b54925cf1
Revises: 41053f363323
Create Date: 2025-12-20 15:12:44.564854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92b54925cf1'
down_revision: Union[str, Sequence[str], None] = '41053f363323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('comments', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.alter_column('cards', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
